[package]
name = "rubik"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "A Rubik's cube library"
repository = "https://github.com/TN19N/rubik"
homepage = "https://github.com/TN19N/rubik"
documentation = "https://docs.rs/rubik"
readme = "README.md"

[dependencies]
