[package]
name = "rubik"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
description = "A Rubik's cube library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
