name: Publish

on:
  workflow_run:
    workflows: [Test]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: publish
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
